# 💰 AWS Cost Projection Report

**Environment:** ${environment} | **Region:** ${region} | **Project:** ${project}  
**Generated:** ${timestamp}

## 📊 Cost Summary

| Metric | Amount |
|--------|--------|
| **Monthly Cost** | $${format("%.2f", total_monthly)} USD |
| **Annual Projection** | $${format("%.2f", total_annual)} USD |
%{if budget_limit > 0}| **Budget Limit** | $${format("%.2f", budget_limit)} USD |
| **Budget Utilization** | ${format("%.1f", budget_utilization)}% |%{endif}

%{if budget_limit > 0}
## 🚦 Budget Status

%{if budget_critical}🔴 **CRITICAL**: Cost projection exceeds budget limit!%{else}%{if budget_warning}🟡 **WARNING**: Cost projection at ${format("%.1f", budget_utilization)}% of budget limit%{else}🟢 **HEALTHY**: Within budget limits%{endif}%{endif}
%{endif}

## 🔧 Service Breakdown

| Service | Monthly Cost | Percentage |
|---------|--------------|------------|
%{for service, cost in service_costs}| ${title(service)} | $${format("%.2f", cost)} | ${format("%.1f", service_percentages[service])}% |
%{endfor}| **TOTAL** | **$${format("%.2f", total_monthly)}** | **100.0%** |

## 📈 Resource Usage Details

| Resource | Usage |
|----------|-------|
| S3 Storage | ${resource_details.s3_storage_gb} GB |
| CloudFront Data Transfer | ${resource_details.cloudfront_data_gb} GB |
| HTTPS Requests | ${format("%.0f", resource_details.cloudfront_requests)} requests |
| WAF Protection | ${resource_details.waf_enabled ? "Enabled" : "Disabled"} |
| Route53 DNS | ${resource_details.route53_enabled ? "Enabled" : "Disabled"} |
| KMS Encryption | ${resource_details.kms_enabled ? "Enabled" : "Disabled"} |
| Cross-Region Replication | ${resource_details.cross_region_repl ? "Enabled" : "Disabled"} |
| Environment Multiplier | ${resource_details.environment_multiplier}x |

## 🎯 Cost Optimization Recommendations

%{if total_monthly > 100}- Consider Reserved Instances for predictable workloads to reduce costs by 30-60%
%{endif}%{if !resource_details.cross_region_repl && environment == "prod"}- Enable cross-region replication for disaster recovery in production
%{endif}%{if service_costs.cloudfront > service_costs.s3 * 3}- Review CloudFront caching settings to optimize data transfer costs
%{endif}%{if budget_limit > 0 && budget_utilization > 80}- Budget utilization high - consider cost optimization measures
%{endif}%{if environment == "dev"}- Development environment - consider scheduled shutdown during non-business hours
%{endif}

## 📋 Next Steps

1. **Review** service costs and identify optimization opportunities
2. **Monitor** actual usage vs. projections
3. **Optimize** high-cost services if budget constraints exist
4. **Plan** for scaling costs as usage grows

---

*Report generated by Cost Projection Module v1.0*  
*Pricing based on AWS us-east-1 region as of 2024*