name: PR Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read
  statuses: write

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Validate PR title follows Conventional Commits
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Require scope (optional, set to false to make scope optional)
          requireScope: false
          # Subjects shouldn't start with uppercase
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the PR title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          # Ignore PRs with these labels
          ignoreLabels: |
            bot
            dependencies
          # WIP detection
          wip: true

  pr-comment:
    name: Comment on Invalid PR
    runs-on: ubuntu-latest
    needs: validate-pr-title
    if: failure()
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          message: |
            ## ❌ PR Title Validation Failed

            Your PR title doesn't follow [Conventional Commits](https://www.conventionalcommits.org/) format.

            **Required format**: `<type>(<scope>): <description>`

            **Valid types**:
            - `feat` - New feature
            - `fix` - Bug fix
            - `docs` - Documentation changes
            - `refactor` - Code refactoring
            - `perf` - Performance improvement
            - `test` - Test changes
            - `chore` - Build/tooling changes
            - `ci` - CI configuration changes
            - `style` - Code style changes
            - `build` - Build system changes
            - `revert` - Revert previous commit

            **Examples**:
            - ✅ `feat(s3): add bucket lifecycle policies`
            - ✅ `fix(iam): correct role trust policy`
            - ✅ `docs: update deployment guide`
            - ✅ `refactor: simplify module structure`
            - ❌ `Added new feature` (no type)
            - ❌ `Feat: new feature` (type should be lowercase)
            - ❌ `feat: Add new feature` (description should start with lowercase)

            **Scope is optional**: `fix: resolve deployment issue` is valid

            Please update your PR title and the check will re-run automatically.
